// Data for countries and cities
export const countries = [
    "Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla","Antigua & Barbuda","Argentina","Armenia","Aruba",
    "Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin",
    "Bermuda","Bhutan","Bolivia","Bosnia & Herzegovina","Botswana","Brazil","British Virgin Islands","Brunei","Bulgaria",
    "Burkina Faso","Burundi","Cambodia","Cameroon","Cape Verde","Cayman Islands","Chad","Chile","China","Colombia","Congo",
    "Cook Islands","Costa Rica","Cote D Ivoire","Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic","Denmark","Djibouti",
    "Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Estonia","Ethiopia","Falkland Islands",
    "Faroe Islands","Fiji","Finland","France","French Polynesia","French West Indies","Gabon","Gambia","Georgia","Germany",
    "Ghana","Gibraltar","Greece","Greenland","Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana",
    "Haiti","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel",
    "Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos","Latvia","Lebanon",
    "Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia",
    "Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat",
    "Morocco","Mozambique","Namibia","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua",
    "Niger","Nigeria","Norway","Oman","Pakistan","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines",
    "Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda","Saint Pierre & Miquelon","Samoa",
    "San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia",
    "South Africa","South Korea","Spain","Sri Lanka","St Kitts & Nevis","St Lucia","St Vincent","St. Lucia","Sudan",
    "Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor L'Este","Togo",
    "Tonga","Trinidad & Tobago","Tunisia","Turkey","Turkmenistan","Turks & Caicos","Uganda","Ukraine","United Arab Emirates",
    "United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Virgin Islands (US)","Yemen","Zambia","Zimbabwe"
];

export const cities = [
    { country: "Afghanistan", cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"] },
    { country: "Albania", cities: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier"] },
    { country: "Algeria", cities: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"] },
    { country: "Andorra", cities: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana"] },
    { country: "Angola", cities: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"] },
    { country: "Anguilla", cities: ["The Valley"] },
    { country: "Antigua & Barbuda", cities: ["St. John's"] },
    { country: "Argentina", cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"] },
    { country: "Armenia", cities: ["Yerevan", "Gyumri", "Vanadzor", "Hrazdan", "Abovyan"] },
    { country: "Aruba", cities: ["Oranjestad", "San Nicolas", "Santa Cruz", "Paradera", "Noord"] },
    { country: "Australia", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"] },
    { country: "Austria", cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"] },
    { country: "Azerbaijan", cities: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran"] },
    { country: "Bahamas", cities: ["Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour"] },
    { country: "Bahrain", cities: ["Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town"] },
    { country: "Bangladesh", cities: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"] },
    { country: "Barbados", cities: ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Bathsheba"] },
    { country: "Belarus", cities: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Hrodna"] },
    { country: "Belgium", cities: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"] },
    { country: "Belize", cities: ["Belize City", "San Ignacio", "Orange Walk Town", "Belmopan", "Dangriga"] },
    { country: "Benin", cities: ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon"] },
    { country: "Bermuda", cities: ["Hamilton", "St. George's", "Somerset Village"] },
    { country: "Bhutan", cities: ["Thimphu", "Phuntsholing", "Punakha", "Gelephu", "Paro"] },
    { country: "Bolivia", cities: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "Oruro"] },
    { country: "Bosnia & Herzegovina", cities: ["Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica"] },
    { country: "Botswana", cities: ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe"] },
    { country: "Brazil", cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"] },
    { country: "British Virgin Islands", cities: ["Road Town", "Spanish Town", "Kingstown"] },
    { country: "Brunei", cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar"] },
    { country: "Bulgaria", cities: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"] },
    { country: "Burkina Faso", cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya"] },
    { country: "Burundi", cities: ["Bujumbura", "Gitega", "Ngozi", "Ruyigi", "Kayanza"] },
    { country: "Cambodia", cities: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"] },
    { country: "Cameroon", cities: ["Douala", "Yaoundé", "Garoua", "Bamenda", "Maroua"] },
    { country: "Cape Verde", cities: ["Praia", "Mindelo", "Santa Maria", "Espargos", "Assomada"] },
    { country: "Cayman Islands", cities: ["George Town", "West Bay", "Bodden Town", "East End", "North Side"] },
    { country: "Chad", cities: ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo"] },
    { country: "Chile", cities: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"] },
    { country: "China", cities: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"] },
    { country: "Colombia", cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"] },
    { country: "Congo", cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Oyo", "Owando"] },
    { country: "Cook Islands", cities: ["Avarua"] },
    { country: "Costa Rica", cities: ["San José", "Alajuela", "Cartago", "Heredia", "Liberia"] },
    { country: "Cote D Ivoire", cities: ["Abidjan", "Yamoussoukro", "Bouaké", "Daloa", "San Pedro"] },
    { country: "Croatia", cities: ["Zagreb", "Split", "Rijeka", "Osijek", "Dubrovnik"] },
    { country: "Cruise Ship", cities: [] },
    { country: "Cuba", cities: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Cienfuegos"] },
    { country: "Cyprus", cities: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"] },
    { country: "Czech Republic", cities: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"] },
    { country: "Denmark", cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"] },
    { country: "Djibouti", cities: ["Djibouti", "Ali Sabieh", "Tadjourah", "Doraleh", "Arta"] },
    { country: "Dominica", cities: ["Roseau"] },
    { country: "Dominican Republic", cities: ["Santo Domingo", "Santiago", "La Romana", "Puerto Plata", "San Pedro de Macorís"] },
    { country: "Ecuador", cities: ["Quito", "Guayaquil", "Cuenca", "Manta", "Loja"] },
    { country: "Egypt", cities: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh", "Luxor"] },
    { country: "El Salvador", cities: ["San Salvador", "Santa Ana", "San Miguel", "La Libertad", "Sonsonate"] },
    { country: "Equatorial Guinea", cities: ["Malabo", "Bata", "Ebebiyin", "Luba", "Aconibe"] },
    { country: "Estonia", cities: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"] },
    { country: "Ethiopia", cities: ["Addis Ababa", "Dire Dawa", "Mekelle", "Bahir Dar", "Gondar"] },
    { country: "Falkland Islands", cities: ["Stanley"] },
    { country: "Faroe Islands", cities: ["Tórshavn", "Klaksvík", "Runavík", "Vágur", "Sørvágur"] },
    { country: "Fiji", cities: ["Suva", "Nadi", "Lautoka", "Labasa", "Savusavu"] },
    { country: "Finland", cities: ["Helsinki", "Espoo", "Tampere", "Oulu", "Vantaa"] },
    { country: "France", cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"] },
    { country: "French Polynesia", cities: ["Papeete", "Faaa", "Punaauia", "Moorea", "Bora Bora"] },
    { country: "French West Indies", cities: ["Fort-de-France", "Pointe-à-Pitre", "Les Abymes", "Le Lamentin", "Saint-Martin"] },
    { country: "Gabon", cities: ["Libreville", "Port-Gentil", "Franceville", "Omboué", "Makokou"] },
    { country: "Gambia", cities: ["Banjul", "Serekunda", "Brikama", "Bakau", "Mansakonko"] },
    { country: "Georgia", cities: ["Tbilisi", "Batumi", "Zugdidi", "Rustavi", "Kutaisi"] },
    { country: "Germany", cities: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne"] },
    { country: "Ghana", cities: ["Accra", "Kumasi", "Takoradi", "Tamale", "Cape Coast"] },
    { country: "Gibraltar", cities: ["Gibraltar"] },
    { country: "Greece", cities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"] },
    { country: "Greenland", cities: ["Nuuk", "Sisimiut", "Ilulissat", "Qaqortoq", "Aasiaat"] },
    { country: "Grenada", cities: ["St. George's", "Gouyave", "Grenville", "Carriacou", "Hillsborough"] },
    { country: "Guam", cities: ["Hagåtña", "Dededo", "Tamuning", "Yigo", "Barrigada"] },
    { country: "Guatemala", cities: ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla"] },
    { country: "Guernsey", cities: ["St. Peter Port", "St. Sampson", "St. Martin", "St. Andrew", "St. Pierre du Bois"] },
    { country: "Guinea", cities: ["Conakry", "Kankan", "Nzérékoré", "Kindia", "Labe"] },
    { country: "Guinea Bissau", cities: ["Bissau", "Bafata", "Gabu", "Cacheu", "Bolama"] },
    { country: "Guyana", cities: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Rose Hall"] },
    { country: "Haiti", cities: ["Port-au-Prince", "Cap-Haïtien", "Jacmel", "Les Cayes", "Gonaïves"] },
    { country: "Honduras", cities: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "El Progreso"] },
    { country: "Hong Kong", cities: ["Hong Kong"] },
    { country: "Hungary", cities: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"] },
    { country: "Iceland", cities: ["Reykjavík", "Kopavogur", "Hafnarfjordur", "Akureyri", "Selfoss"] },
    { country: "India", cities: ["New Delhi", "Mumbai", "Bengaluru", "Kolkata", "Chennai"] },
    { country: "Indonesia", cities: ["Jakarta", "Surabaya", "Bandung", "Medan", "Yogyakarta"] },
    { country: "Iran", cities: ["Tehran", "Isfahan", "Shiraz", "Tabriz", "Mashhad"] },
    { country: "Iraq", cities: ["Baghdad", "Mosul", "Basra", "Kirkuk", "Erbil"] },
    { country: "Ireland", cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"] },
    { country: "Isle of Man", cities: ["Douglas", "Onchan", "Port Erin", "Ramsey", "Peel"] },
    { country: "Israel", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Be'er Sheva", "Netanya"] },
    { country: "Italy", cities: ["Rome", "Milan", "Naples", "Turin", "Palermo"] },
    { country: "Jamaica", cities: ["Kingston", "Montego Bay", "Mandeville", "Ocho Rios", "Negril"] },
    { country: "Japan", cities: ["Tokyo", "Osaka", "Kyoto", "Nagoya", "Fukuoka"] },
    { country: "Jersey", cities: ["St. Helier", "St. Aubin", "St. Brelade", "St. Peter", "St. Ouen"] },
    { country: "Jordan", cities: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"] },
    { country: "Kazakhstan", cities: ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe"] },
    { country: "Kenya", cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"] },
    { country: "Kuwait", cities: ["Kuwait City", "Al Ahmadi", "Jahra", "Farwaniyah", "Mubarak Al-Kabeer"] },
    { country: "Kyrgyz Republic", cities: ["Bishkek", "Osh", "Jalal-Abad", "Karabalta", "Karakol"] },
    { country: "Laos", cities: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet", "Xam Neua"] },
    { country: "Latvia", cities: ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Ventspils"] },
    { country: "Lebanon", cities: ["Beirut", "Tripoli", "Sidon", "Tyre", "Zahle"] },
    { country: "Lesotho", cities: ["Maseru", "Teyateyaneng", "Maputsoe", "Leribe", "Berea"] },
    { country: "Liberia", cities: ["Monrovia", "Gbarnga", "Buchanan", "Harper", "Zwedru"] },
    { country: "Libya", cities: ["Tripoli", "Benghazi", "Misrata", "Sebha", "Al Khums"] },
    { country: "Liechtenstein", cities: ["Vaduz", "Schaan", "Balzers", "Eschen", "Schaanwald"] },
    { country: "Lithuania", cities: ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai", "Panevėžys"] },
    { country: "Luxembourg", cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Echternach", "Wiltz"] },
    { country: "Macau", cities: ["Macau"] },
    { country: "Macedonia", cities: ["Skopje", "Bitola", "Ohrid", "Kumanovo", "Tetovo"] },
    { country: "Madagascar", cities: ["Antananarivo", "Toamasina", "Antsiranana", "Mahajanga", "Fianarantsoa"] },
    { country: "Malawi", cities: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"] },
    { country: "Malaysia", cities: ["Kuala Lumpur", "George Town", "Ipoh", "Kota Kinabalu", "Kuching"] },
    { country: "Maldives", cities: ["Malé", "Addu City", "Fuvahmulah", "Dhidhdhoo", "Kulhudhuffushi"] },
    { country: "Mali", cities: ["Bamako", "Ségou", "Kayes", "Gao", "Koutiala"] },
    { country: "Malta", cities: ["Valletta", "Birkirkara", "Sliema", "Mosta", "Qormi"] },
    { country: "Mauritania", cities: ["Nouakchott", "Nouadhibou", "Kiffa", "Zouérat", "Atar"] },
    { country: "Mauritius", cities: ["Port Louis", "Curepipe", "Quatre Bornes", "Vacoas", "Mahebourg"] },
    { country: "Mexico", cities: ["Mexico City", "Guadalajara", "Monterrey", "Cancun", "Puebla"] },
    { country: "Moldova", cities: ["Chisinau", "Bălți", "Bender", "Rîbnița", "Soroca"] },
    { country: "Monaco", cities: ["Monaco"] },
    { country: "Mongolia", cities: ["Ulaanbaatar", "Erdenet", "Darkhan", "Mörön", "Züünharaa"] },
    { country: "Montenegro", cities: ["Podgorica", "Herceg Novi", "Bijelo Polje", "Nikšić", "Tivat"] },
    { country: "Montserrat", cities: ["Plymouth", "Brades"] },
    { country: "Morocco", cities: ["Casablanca", "Rabat", "Marrakech", "Fes", "Tangier"] },
    { country: "Mozambique", cities: ["Maputo", "Beira", "Nampula", "Tete", "Chimoio"] },
    { country: "Namibia", cities: ["Windhoek", "Swakopmund", "Walvis Bay", "Rundu", "Ongwediva"] },
    { country: "Nepal", cities: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Janakpur"] },
    { country: "Netherlands", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"] },
    { country: "Netherlands Antilles", cities: ["Willemstad", "Kralendijk", "Oranjestad"] },
    { country: "New Caledonia", cities: ["Nouméa", "Dumbéa", "Mont-Dore", "Païta", "Koné"] },
    { country: "New Zealand", cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"] },
    { country: "Nicaragua", cities: ["Managua", "León", "Granada", "Masaya", "Chinandega"] },
    { country: "Niger", cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Diffa"] },
    { country: "Nigeria", cities: ["Lagos", "Abuja", "Port Harcourt", "Kano", "Ibadan"] },
    { country: "Norway", cities: ["Oslo", "Bergen", "Stavanger", "Drammen", "Trondheim"] },
    { country: "Oman", cities: ["Muscat", "Salalah", "Sohar", "Nizwa", "Ibra"] },
    { country: "Pakistan", cities: ["Islamabad", "Karachi", "Lahore", "Rawalpindi", "Faisalabad"] },
    { country: "Palestine", cities: ["Ramallah", "Gaza City", "Hebron", "Nablus", "Jericho"] },
    { country: "Panama", cities: ["Panama City", "Colón", "David", "La Chorrera", "Santiago"] },
    { country: "Papua New Guinea", cities: ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Rabaul"] },
    { country: "Paraguay", cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Encarnación", "Concepción"] },
    { country: "Peru", cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura"] },
    { country: "Philippines", cities: ["Manila", "Quezon City", "Cebu City", "Davao City", "Zamboanga City"] },
    { country: "Poland", cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"] },
    { country: "Portugal", cities: ["Lisbon", "Porto", "Braga", "Aveiro", "Coimbra"] },
    { country: "Puerto Rico", cities: ["San Juan", "Ponce", "Bayamón", "Mayagüez", "Arecibo"] },
    { country: "Qatar", cities: ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal", "Mesaieed"] },
    { country: "Reunion", cities: ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Saint-André", "Saint-Louis"] },
    { country: "Romania", cities: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"] },
    { country: "Russia", cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod"] },
    { country: "Rwanda", cities: ["Kigali", "Butare", "Gisenyi", "Byumba", "Cyangugu"] },
    { country: "Saint Pierre & Miquelon", cities: ["Saint-Pierre", "Miquelon"] },
    { country: "Samoa", cities: ["Apia", "Faleolo", "Lalomanu"] },
    { country: "San Marino", cities: ["San Marino"] },
    { country: "Saudi Arabia", cities: ["Riyadh", "Jeddah", "Mecca", "Dammam", "Khobar"] },
    { country: "Senegal", cities: ["Dakar", "Saint-Louis", "Touba", "Ziguinchor", "Thiès"] },
    { country: "Serbia", cities: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"] },
    { country: "Seychelles", cities: ["Victoria", "Bel Ombre", "Anse Boileau", "Baie Sainte Anne", "La Digue"] },
    { country: "Sierra Leone", cities: ["Freetown", "Bo", "Kenema", "Makeni", "Kailahun"] },
    { country: "Singapore", cities: ["Singapore"] },
    { country: "Sint Maarten", cities: ["Philipsburg", "Maho", "Simpson Bay", "Cole Bay", "Cupecoy"] },
    { country: "Slovakia", cities: ["Bratislava", "Košice", "Nitra", "Prešov", "Trnava"] },
    { country: "Slovenia", cities: ["Ljubljana", "Maribor", "Celje", "Kranj", "Nova Gorica"] },
    { country: "Solomon Islands", cities: ["Honiara", "Gizo", "Auki", "Tulagi", "Noro"] },
    { country: "Somalia", cities: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Baidoa"] },
    { country: "South Africa", cities: ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Port Elizabeth"] },
    { country: "South Georgia and the South Sandwich Islands", cities: [] },
    { country: "South Sudan", cities: ["Juba", "Malakal", "Wau", "Rumbek", "Yei"] },
    { country: "Spain", cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao"] },
    { country: "Sri Lanka", cities: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"] },
    { country: "Sudan", cities: ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "Kassala"] },
    { country: "Suriname", cities: ["Paramaribo", "Nieuw Nickerie", "Moengo", "Brokopondo", "Albina"] },
    { country: "Sweden", cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"] },
    { country: "Switzerland", cities: ["Zurich", "Geneva", "Bern", "Basel", "Lausanne"] },
    { country: "Syria", cities: ["Damascus", "Aleppo", "Homs", "Latakia", "Deir ez-Zor"] },
    { country: "Taiwan", cities: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"] },
    { country: "Tajikistan", cities: ["Dushanbe", "Khujand", "Kurgan-Tyube", "Istaravshan", "Tursunzoda"] },
    { country: "Tanzania", cities: ["Dodoma", "Dar es Salaam", "Arusha", "Mbeya", "Mwanza"] },
    { country: "Thailand", cities: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nakhon Ratchasima"] },
    { country: "Timor-Leste", cities: ["Dili", "Baucau", "Liquiçá", "Viqueque", "Oecusse"] },
    { country: "Togo", cities: ["Lomé", "Kara", "Sokodé", "Atakpamé", "Tsévié"] },
    { country: "Tokelau", cities: [] },
    { country: "Tonga", cities: ["Nukuʻalofa"] },
    { country: "Trinidad and Tobago", cities: ["Port of Spain", "San Fernando", "Scarborough", "Chaguanas", "Arima"] },
    { country: "Tunisia", cities: ["Tunis", "Sfax", "Sousse", "Kairouan", "Monastir"] },
    { country: "Turkey", cities: ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"] },
    { country: "Turkmenistan", cities: ["Ashgabat", "Turkmenabat", "Mary", "Dashoguz", "Balkanabat"] },
    { country: "Tuvalu", cities: ["Funafuti"] },
    { country: "Uganda", cities: ["Kampala", "Entebbe", "Jinja", "Mbarara", "Gulu"] },
    { country: "Ukraine", cities: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Lviv"] },
    { country: "United Arab Emirates", cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras al-Khaimah"] },
    { country: "United Kingdom", cities: ["London", "Manchester", "Birmingham", "Glasgow", "Liverpool"] },
    { country: "United States", cities: ["New York", "Los Angeles", "Chicago", "Houston", "San Francisco"] },
    { country: "Uruguay", cities: ["Montevideo", "Salto", "Paysandú", "Rivera", "Tacuarembó"] },
    { country: "Uzbekistan", cities: ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Andijan"] },
    { country: "Vanuatu", cities: ["Port Vila", "Luganville", "Norsup", "Sola", "Lenakel"] },
    { country: "Venezuela", cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Margarita Island"] },
    { country: "Vietnam", cities: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue", "Can Tho"] },
    { country: "Western Sahara", cities: ["El Aaiún", "Dakhla"] },
    { country: "Yemen", cities: ["Sana'a", "Aden", "Taiz", "Mukalla", "Hodeida"] },
    { country: "Zambia", cities: ["Lusaka", "Ndola", "Kitwe", "Livingstone", "Chingola"] },
    { country: "Zimbabwe", cities: ["Harare", "Bulawayo", "Mutare", "Gweru", "Kwekwe"] }
  ]

