export const countries = [
    "Egypt",
    "Saudi Arabia",
    "United Arab Emirates",
    "Morocco",
    "Jordan",
    "Lebanon",
    "Tunisia",
    "Algeria",
    "Iraq",
    "Qatar",
    "Kuwait",
    "Oman",
    "Bahrain",
    "Libya",
    "Syria",
    "Yemen",
    "Sudan",
    "Palestine"
];

export const cities = {
    Egypt: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh", "Luxor"],
    SaudiArabia: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
    UnitedArabEmirates: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
    Morocco: ["Casablanca", "Rabat", "Marrakesh", "Tangier", "Fes"],
    Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Mafraq"],
    Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Zahle"],
    Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan", "Gabes"],
    Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
    Iraq: ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
    Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal"],
    Kuwait: ["Kuwait City", "Al Ahmadi", "Hawalli", "Al Farwaniyah", "Al Jahra"],
    Oman: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur"],
    Bahrain: ["Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town"],
    Libya: ["Tripoli", "Benghazi", "Misrata", "Al Bayda", "Zawiya"],
    Syria: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
    Yemen: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Mukalla"],
    Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "Kassala"],
    Palestine: ["Jerusalem", "Gaza City", "Ramallah", "Hebron", "Nablus"]
};
