export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_PRODUCT_QUANITITY = 'UPDATE_PRODUCT_QUANITITY';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM';