export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM';